name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
         tar xzf l_cprof_p_11.1.056.tgz
         ls
         cd Testin
         #make out
      shell: bash
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
